//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tashlumTbl1
    {
        public int idTorem { get; set; }
        public Nullable<int> sum { get; set; }
        public Nullable<int> idSug { get; set; }
        public Nullable<int> misTashlum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> sumKolel { get; set; }
        public string name { get; set; }
        public string idAshrai { get; set; }
        public string sugAshrai { get; set; }
        public string numAshrai { get; set; }
        public Nullable<System.DateTime> tokef { get; set; }
        public string idBalAshrai { get; set; }
        public Nullable<int> cvv { get; set; }
        public Nullable<bool> kabala { get; set; }
        public string nameKabala { get; set; }
        public string namAccount { get; set; }
        public Nullable<int> numSnif { get; set; }
        public string misCheck { get; set; }
        public Nullable<int> sum1 { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<int> numBank { get; set; }
        public string namAccount1 { get; set; }
        public Nullable<int> numSnif1 { get; set; }
        public string misCheck1 { get; set; }
        public Nullable<int> sum11 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<int> numBank1 { get; set; }
        public string namAccount2 { get; set; }
        public Nullable<int> numSnif2 { get; set; }
        public string misCheck2 { get; set; }
        public Nullable<int> sum12 { get; set; }
        public Nullable<int> numBank2 { get; set; }
        public string namAccount3 { get; set; }
        public Nullable<int> numSnif3 { get; set; }
        public string misCheck3 { get; set; }
        public Nullable<int> sum13 { get; set; }
        public Nullable<System.DateTime> date3 { get; set; }
        public Nullable<int> numBank3 { get; set; }
        public string namAccount4 { get; set; }
        public Nullable<int> numSnif4 { get; set; }
        public string misCheck4 { get; set; }
        public Nullable<int> sum14 { get; set; }
        public Nullable<System.DateTime> date4 { get; set; }
        public Nullable<int> numBank4 { get; set; }
        public string namAccount5 { get; set; }
        public Nullable<int> numSnif5 { get; set; }
        public string misCheck5 { get; set; }
        public Nullable<int> sum15 { get; set; }
        public Nullable<System.DateTime> date5 { get; set; }
        public Nullable<int> numBank5 { get; set; }
        public string namAccount6 { get; set; }
        public Nullable<int> numSnif6 { get; set; }
        public string misCheck6 { get; set; }
        public Nullable<int> sum16 { get; set; }
        public Nullable<System.DateTime> date6 { get; set; }
        public Nullable<int> numBank6 { get; set; }
        public string namAccount7 { get; set; }
        public Nullable<int> numSnif7 { get; set; }
        public string misCheck7 { get; set; }
        public Nullable<int> sum17 { get; set; }
        public Nullable<System.DateTime> date7 { get; set; }
        public Nullable<int> numBank7 { get; set; }
        public string namAccount8 { get; set; }
        public Nullable<int> numSnif8 { get; set; }
        public string misCheck8 { get; set; }
        public Nullable<int> sum18 { get; set; }
        public Nullable<System.DateTime> date8 { get; set; }
        public Nullable<int> numBank8 { get; set; }
        public string namAccount9 { get; set; }
        public Nullable<int> numSnif9 { get; set; }
        public string misCheck9 { get; set; }
        public Nullable<int> sum19 { get; set; }
        public Nullable<System.DateTime> date9 { get; set; }
        public Nullable<int> numBank9 { get; set; }
        public Nullable<int> numTofes { get; set; }
        public string numAsmachta { get; set; }
    
        public virtual EmzeiTashlum EmzeiTashlum { get; set; }
        public virtual tblTorem tblTorem { get; set; }
    }
}
